# Generated by Django 5.1.1 on 2024-09-08 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('noBuses', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Busstop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=10)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIHapp.route')),
            ],
        ),
    ]
