# Generated by Django 5.0.7 on 2024-09-10 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SIHapp', '0002_remove_route_nobuses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busstop',
            old_name='bus',
            new_name='route',
        ),
    ]
