# Generated by Django 5.1.1 on 2024-09-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIHapp', '0003_rename_bus_busstop_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busstop',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
