# Generated by Django 5.1.1 on 2024-09-13 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIHapp', '0004_alter_busstop_latitude_alter_busstop_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busstop',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SIHapp.route'),
        ),
    ]
