# Generated by Django 5.1.1 on 2024-09-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIHapp', '0006_remove_busstop_route_route_bus_stop'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='bus_quantity',
            field=models.IntegerField(default=100),
        ),
    ]
