# Generated by Django 5.1.1 on 2024-09-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIHapp', '0007_route_bus_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busstop',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
