# Generated by Django 5.1.1 on 2024-09-16 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIHapp', '0008_alter_busstop_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('plate', models.CharField(max_length=100)),
                ('ac', models.BooleanField(default=False)),
                ('route', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='SIHapp.route')),
            ],
        ),
    ]
